### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by pavel-rosputko** [isavita/naive-dice#1]
hey, we liked your solution very much. we have a concern related to optimistic locking

let's imagine we have frequent reserve requests: 10k requests per minute. the excessive rate of errors like `(Ecto.StaleModelError) attempted to update a stale model` would affect the conversation rate of purchases. Could you please implement a fix.

**Comment by isavita** [comment]
Hi @marty-stranger
Thank you for the review. I added PR #2 that replace the optimistic locking with pessimistic locking.
The main rational is if we expect many collisions pessimistic locking would be more efficient than rolling back a lot of the transactions ([more detailed explanation](https://stackoverflow.com/a/129380)).
What do you think?

**Comment by isavita** [comment]
If you are fine with the solution, there is #3 for removing the column as second step after that one is deployed.

**Comment by isavita** [comment]
Another approach might be to have threshold of 1000 and activate the look only if the *available_tickets_count* is under the threshold.

**Comment by isavita** [comment]
Another alternative might be to have threshold that triggers different strategy. For example when they are less than N available tickets to make a pessimistic lock and to have count of the tickets for the schema to account for missing from the previous updates.

**Comment by pavel-rosputko** [comment]
your solution is correct, thank you!
